version: '3'

services:
  app:
    depends_on:
      - postgres
      - redis
    image: docuseal/local
    ports:
      - "3000:3000"
    volumes:
      - .:/data
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/docuseal
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    depends_on:
      - postgres
      - redis
    image: docuseal/local
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/data
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/docuseal
      REDIS_URL: redis://redis:6379/0
    working_dir: /app

  postgres:
    image: postgres:15
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    volumes:
      - 'redis_data:/data'

volumes:
  redis_data: